# Note: This is a swagger file describing an API endpoint.
# The easiest way to edit this is to use the online editor at
#   http://editor.swagger.io/
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Noseplug API
paths:
  /events:
    get:
      responses:
        200:
          description: Returns an array of all odor events.
          schema:
            type: array
            items:
              $ref: "#/definitions/Event"
    post:
      parameters:
        - name: Event
          in: body
          description: A JSON Event object. EventID should be omitted.
          required: true
          schema:
            $ref: "#/definitions/Event"
      responses:
        201:
          description: The odor event was successfully created.
          # TODO return URL of the newly created resource

  /events/{EventId}:
    parameters:
      - $ref: "#/parameters/EventId"
    get:
      responses:
        200:
          description: Return the odor event with the given ID.
          schema:
            $ref: "#/definitions/Event"
    put:
      parameters:
        - name: Event
          in: body
          description: A JSON Event object. EventID must match the existing ID.
          required: true
          schema:
            $ref: "#/definitions/Event"
      responses:
        200:
          description: The odor event was successfully updated with the given information.

  /events/{EventId}/reports:
    parameters:
      - $ref: "#/parameters/EventId"
    get:
      responses:
        200:
          description: Returns an array of all reports associated with this odor event.
          schema:
            type: array
            items:
              $ref: "#/definitions/Report"
    post:
      parameters:
        - name: Report
          in: body
          description: A Report JSON object. ReportNum must be omitted.
          required: true
          schema:
            $ref: "#/definitions/Report"
      responses:
        201:
          description: The report was successfully added to the odor event.
          # TODO: Should get back the URL of the new odor report through a Location HTTP header. That can be used to properly complete the Report object with ReportNum.

  /events/{EventId}/reports/{ReportNum}:
    parameters:
      - $ref: "#/parameters/EventId"
      - $ref: "#/parameters/ReportNum"
    get:
      responses:
        200:
          description: Return the report wih the given number.
          schema:
            $ref: "#/definitions/Report"
    put:
      parameters:
        - name: Report
          in: body
          description: A Report JSON object.
          required: true
          schema:
            $ref: "#/definitions/Report"
      responses:
        200:
          description: The report was successfully updated.

  /events/{EventId}/wallposts:
    parameters:
      - $ref: "#/parameters/EventId"
    get:
      responses:
        200:
          description: Returns an array of all posts submitted to the odor event's wall.
          schema:
            type: array
            items:
              $ref: "#/definitions/Wallpost"
    post:
      parameters:
        - name: Wallpost
          in: body
          description: A Wallpost JSON object. WallpostNum must be omitted.
          required: true
          schema:
            $ref: "#/definitions/Wallpost"
      responses:
        201:
          description: The wallpost was successfully posted to the odor event's wall.
          # TODO: same as POST /events/{EventId}/reports

  /events/{EventId}/wallposts/{WallpostNum}:
    parameters:
      - $ref: "#/parameters/EventId"
      - $ref: "#/parameters/WallpostNum"
    get:
      responses:
        200:
          description: Returns the wallpost with the given number.
          schema:
            $ref: "#/definitions/Wallpost"
    put:
      parameters:
        - name: Wallpost
          in: body
          description: Replace an existing wallpost with a new version.
          required: true
          schema:
            $ref: "#/definitions/Wallpost"
      responses:
        200:
          description: The wallpost was updated.

  /events/{EventId}/subscribers:
    parameters:
      - $ref: "#/parameters/EventId"
    get:
      responses:
        200:
          description: Returns an array of user IDs of users subscribed to the odor event.
          schema:
            type: array
            items:
              $ref: "#/definitions/Id"

  /users/{UserId}:
    parameters:
      - $ref: "#/parameters/UserId"
    get:
      responses:
        200:
          description: Returns the profile of the user with the given ID.
          schema:
            $ref: "#/definitions/User"

  /users/{UserId}/subscriptions:
    parameters:
      - $ref: "#/parameters/UserId"
    get:
      responses:
        200:
          description: Returns an array of event IDs that the user is subscribed to.
          schema:
            type: array
            items:
              $ref: "#/definitions/Id"
    post:
      parameters:
        - name: EventId
          in: body
          description: The ID of the odor event to subscribe to.
          required: true
          schema:
            $ref: "#/definitions/Id"
      responses:
        201:
          description: Added the odor event to the user's list of subscriptions.

  /users/{UserId}/subscriptions/{EventId}:
    parameters:
      - $ref: "#/parameters/UserId"
      - $ref: "#/parameters/EventId"
    delete:
      responses:
        200:
          description: The user successfully unsubscribed from the odor event with the given ID.

parameters:
  UserId:
    name: UserId
    in: path
    description: A UUID identifying a Noseplug user.
    required: true
    type: string
    format: uuid

  EventId:
    name: EventId
    in: path
    description: A UUID identifying a Noseplug odor event.
    required: true
    type: string
    format: uuid

  ReportNum:
    name: ReportNum
    in: path
    description: A number identifying a Noseplug odor report of an odor event. Starts at 1 and increases monotonically.
    required: true
    type: integer
    format: int64

  WallpostNum:
    name: WallpostNum
    in: path
    description: A number identifying a Noseplug wallpost on an odor event. Starts at 1 and increases monotonically.
    required: true
    type: integer
    format: int64

definitions:
  Id:
    type: string
    format: uuid
    description: A UUID for identifying a noseplug user or odor event.

  Num:
    type: integer
    format: int64
    description: A 64-bit integer number for identifying a Noseplug report or wallpost within an odor event. These are generally monotonically increasing, starting from 1, and should not be chosen by the client.

  Odor:
    type: object
    properties:
      Strength:
        type: string
        description: "The strength of an odor. Must be one of the following: LIGHT, MODERATE, STRONG, VERY_STRONG"

      Type:
        type: string
        description: "The type of an odor. Must be one of the following: FRAGRANT, PUNGENT, PUTRID, FECAL, FISHY, EARTHY, PINE, CHEMICAL, MEDICINAL, SULFUR, OTHER"

  Location:
    type: object
    properties:
      Latitude:
        type: number
        format: double
        description: The latitude component of the location. North is positive and south is negative.
      Longitude:
        type: number
        format: double
        description: The longitude component of the location. East is positive and west is negative.

  Report:
    type: object
    properties:
      ReportNum:
        $ref: "#/definitions/Num"
      UserId:
        $ref: "#/definitions/Id"
      EventId:
        $ref: "#/definitions/Id"
      Location:
        $ref: "#/definitions/Location"
      Odor:
        $ref: "#/definitions/Odor"
      FilingTime:
        type: string
        format: date-time
        description: The UTC time when the report was created.

  Event:
    type: object
    properties:
      EventId:
        $ref: "#/definitions/Id"
      Name:
        type: string
        description: The user-submitted title for an odor event.
      OwnerId:
        $ref: "#/definitions/Id"
      AdminIds:
        type: array
        description: An array of the user IDs of the administrators of an odor event.
        items:
          $ref: "#/definitions/Id"

  Wallpost:
    type: object
    properties:
      WallpostNum:
        $ref: "#/definitions/Num"
      UserId:
        $ref: "#/definitions/Id"
      EventId:
        $ref: "#/definitions/Id"
      SubmitTime:
        type: string
        format: date-time
        description: The UTC time when the message was submitted.
      Content:
        type: string
        description: The content of a message posted by a user.

  User:
    type: object
    properties:
      UserId:
        $ref: "#/definitions/Id"
      # TODO: where do we put passwords to update passwords? The API should never return a hashed password, but we need a way to send plain passwords to the API to create user accounts.
      Name:
        type: string
      Email:
        type: string
        format: email
      PhoneNo:
        type: string
        format: tel
      Gender:
        type: string
        description: This can be MALE, FEMALE, or any other alphabetic string entered by the user. It must be normalized to upper case.
