# Note: This is a swagger file describing an API endpoint.
# The easiest way to edit this is to use the online editor at
#   http://editon.swagger.io/
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Noseplug API
paths:
  /events:
    get:
      responses:
        200:
          description: An array of odor events.

  /events/{id}/reports:
    get:
      parameters:
        - $ref: "#/parameters/id"
      responses:
        200:
          description: Returns an array of all reports associated with this odor event.

  /events/{id}/wallposts:
    get:
      parameters:
        - $ref: "#/parameters/id"
      responses:
        200:
          description: Returns an array of all posts submitted to the odor event's wall.
          schema:
            type: array
            items:
              $ref: "#/definitions/WallPost"

  /events/{id}/subscribers:
    get:
      parameters:
        - $ref: "#/parameters/id"
      responses:
        200:
          description: Returns an array of user IDs of users subscribed to the odor event.
          schema:
            type: array
            items:
              $ref: "#/definitions/Id"

  /reports/{id}:
    get:
      parameters:
        - $ref: "#/parameters/id"
      responses:
        200:
          description: Returns the report with the given ID.
          schema:
            $ref: "#/definitions/Report"

parameters:
  id:
    name: id
    in: path
    description: A UUID for identifying a Noseplug resource, such as posts, messages, users, and odor events.
    required: true
    type: string
    format: uuid

definitions:
  Id:
    type: string
    format: uuid
    description: A UUID for identifying a Noseplug resource, such as posts, messages, users, and odor events.

  Odor:
    type: object
    properties:
      Strength:
        type: string
        description: "The strength of an odor. Must be one of the following: LIGHT, MODERATE, STRONG, VERY_STRONG"

      Type:
        type: string
        description: "The type of an odor. Must be one of the following: FRAGRANT, PUNGENT, PUTRID, FECAL, FISHY, EARTHY, PINE, CHEMICAL, MEDICINAL, SULFUR, OTHER"

  Location:
    type: object
    properties:
      Latitude:
        type: number
        format: double
        description: The latitude component of the location. North is positive and south is negative.
      Longitude:
        type: number
        format: double
        description: The longitude component of the location. East is positive and west is negative.

  Report:
    type: object
    properties:
      Id:
        $ref: "#/definitions/Id"
      UserId:
        $ref: "#/definitions/Id"
      EventId:
        $ref: "#/definitions/Id"
      Location:
        $ref: "#/definitions/Location"
      Odor:
        $ref: "#/definitions/Odor"
      FilingTime:
        type: string
        format: date-time
        description: The UTC time when the report was created.

  Event:
    type: object
    properties:
      Id:
        $ref: "#/definitions/Id"
      Name:
        type: string
        description: The user-submitted title for an odor event.
      OwnerId:
        $ref: "#/definitions/Id"
      AdminIds:
        type: array
        description: An array of the user IDs of the administrators of an odor event.
        items:
          $ref: "#/definitions/Id"

  WallPost:
    type: object
    properties:
      Id:
        $ref: "#/definitions/Id"
      UserId:
        $ref: "#/definitions/Id"
      EventId:
        $ref: "#/definitions/Id"
      SubmitTime:
        type: string
        format: date-time
        description: The UTC time when the message was submitted.
      Content:
        type: string
        description: The content of a message posted by a user.
